name: local_data_source
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1

  #Local Data Source
  flutter_secure_storage: ^5.0.2

  #State-Management
  flutter_riverpod: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^1.0.0

flutter:

  
  uses-material-design: true
